package demo;
// Generated Sep 30, 2012 7:24:04 AM by Hibernate Tools 3.2.1.GA



/**
 * InPersons generated by hbm2java
 */
public class InPersons  implements java.io.Serializable {


     private int id;
     private String name,company;
    
    public InPersons() {
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
}


